### ISSUE TITLE
I can't seem to render multiple ReactCountdownClock components on a page

### ISSUE THREAD

**Issue by hoverbird** [pughpugh/react-countdown-clock#1]
Hi there. When rendering 3 of these components on a page (think expiring deals that all have individual timers), I see 3 canvas elements as expected, but only the first one actually draws the countdown clock. The other few are empty. Any idea why that might be the case? Thanks in advance!

**Comment by pughpugh** [comment]
Ahoy! Thanks for reporting this.

I will take a look at this tonight if I can - otherwise, if you come up with a fix, feel free to issue a pull-request.

**Comment by hoverbird** [comment]
Hey! Thanks for taking a look at it. I've moved on from needing to render multiple timers in the same page, but FWIW the issue still remains. I'm an utter noob when it comes to Canvas APIs so I haven't had much luck in diagnosing it. Best of luck!

**Comment by pughpugh** [comment]
Can you post an example of it's usage @hoverbird ?

**Comment by hoverbird** [comment]
Oops, my mistake. I thought bower had updated me to your latest fixversion, but I realized when testing in JS Fiddle it was actually stuck on the last one. All works as expected now; thanks!

**Comment by pughpugh** [comment]
Great stuff, thanks!
