### ISSUE TITLE
Change props (color) without restarting the countdown

### ISSUE THREAD

**Issue by gillchristian** [pughpugh/react-countdown-clock#11]
Hi, the component is awesome! :smile: 

I'm using it to display the time remaining for the user to buy some stuff. I wanted to change the color when a certain time it is about to end but if I pass new props it starts the countdown again. Any ideas on how to solve that?

**Comment by pughpugh** [comment]
Hey - probably of no use to you now, but I'm working through some of the issues over xmas.  The time and colour props changes should now not conflict and reset the timer. This is fixed on master and should be in the next release.

I've added it to the demo - click the timer to prove it works.

http://pughpugh.github.io/react-countdown-clock/

Thanks for your input,
Hugh

**Comment by pughpugh** [comment]
This has now been published to npm. Sorry for the delay and thanks again for your input.
