### ISSUE TITLE
Prop for whether the counter should be paused

### ISSUE THREAD

**Issue by janhartmann** [pughpugh/react-countdown-clock#14]
It would be cool if you could be able to pause the countdown.

I have a use case where the count down is not visible and I wish to control when to start the countdown. Thanks :-)

**Comment by hualet** [comment]
Yeah, this feature would be very helpful.

**Comment by pughpugh** [comment]
Hi,

I've added a couple of new props;

```
paused: React.PropTypes.bool
pausedText: React.PropTypes.string
```

`pausedText` is optional and by default it will just freeze the current time. It's a little troublesome as the paused text string will be of the same font size as the last displayed time. I'd suggest also setting a fixed `fontSize` at the same time as setting the `paused` prop when using `pausedText`.

This is all on master at the moment. I've updated the demo and it should be in the next release I cut.

http://pughpugh.github.io/react-countdown-clock/

Thanks for your input,
Hugh

**Comment by ohmyjersh** [comment]
@pughpugh any idea when you will push a release to npm?  The pause feature would be nice to have.

**Comment by hualet** [comment]
+1

**Comment by pughpugh** [comment]
@ohmyjersh Possibly next week, I'm just finding it hard to make time to test it. I the mean time you can always give it a whirl via the master branch.

**Comment by protoEvangelium** [comment]
@pughpugh Hey Hugh :) I tried to set the paused property = true and the time just keeps on spinning.  Is this implemented in the current release?

**Comment by pughpugh** [comment]
This has now been deployed to npm. The example has been updated (click on the timer to pause it)
