### ISSUE TITLE
Stop from reinitializing on state state change.

### ISSUE THREAD

**Issue by sturoid** [pughpugh/react-countdown-clock#17]
Hi there. Thank you for your work on this. It is great. I'm using the timer in an overlay on the screen that can be hidden and shown. Whenever it is hidden and shown the clock will reinitialize. Do you know of any way to stop it from doing that? Thank you in advance for the help.

**Comment by pughpugh** [comment]
Are you hiding it by toggling css `display` or adding it and removing it from the DOM via react? I think the first would work fine, but the second would cause it to reinitialise every time.

**Comment by sturoid** [comment]
I'm just using jquery to add and remove classes to the container div. So one is fullscreen, one is minimized. Here is the view changer:

  handleChangeExamView() {
    const examEl = $('#course__exam')
    if($(examEl).hasClass('fullscreen')) {
      this.setState({examView: 'minimized'})
      $('#course__exam').removeClass('fullscreen').addClass('minimized')
      document.body.className = ''
    } else if ($(examEl).hasClass('minimized')) {
      this.setState({examView: 'fullscreen'})
      $('#course__exam').removeClass('minimized').addClass('fullscreen')
      document.body.className = 'noscroll'
    }
  }

And the classes:

.fullscreen
  height: 100vh
  position: fixed
  top: 0
  bottom: 0
  left: 0
  right: 0
  overflow-y: scroll
  @media(min-width: 768px)
    padding: 8px 40px 40px 40px
  @media(max-width: 768px)
    padding: 8px 10px 40px 10px

.minimized
  border-bottom: 2px solid $orange
  height: 40px
  position: fixed
  top: 0
  left: 0
  right: 0
  overflow: hidden
  @media(min-width: 768px)
    padding: 8px 40px
  @media(max-width: 768px)
    padding: 8px 10px


The weird thing is, even in minimized view there is still a 40px bar at the top of the screen. If I put the timer there where it never goes out of view/leaves the dom, it still resets every time.

**Comment by emelent** [comment]
I'm still quite new to react, but my fix would be to wrap the ReactCountDownClock component in your own custom component, and then have your component's shouldComponentUpdate(...) method return false, this way your component won't update on any state changes.

`class MyCountDown extends ReactCountDownClock{
    
    shouldComponentUpdate(nextProps, nextState){
        return false;
    }
    
    render(){
        return (<ReactCountDownClock />);
}`

[source](http://stackoverflow.com/questions/24718709/reactjs-does-render-get-called-any-time-setstate-is-called)
