### ISSUE TITLE
can not set the paused and pausedText in React 

### ISSUE THREAD

**Issue by RicardoHuangCHINA** [pughpugh/react-countdown-clock#21]

**Comment by JimmyTT** [comment]
The issue is not that it doesn't work in React; however, when you "npm install --save react-countdown-clock" the version is out of sync with the github repo.

**Comment by pughpugh** [comment]
Thaks @JimmyTT . Yeah indeed this is only on master and has not been published yet. The version there is functionally complete, I've just found no time to test it in recent months. You're welcome to give it a whirl and report any issues.

**Comment by pughpugh** [comment]
This has now been published to npm
