### ISSUE TITLE
Warning: React.createClass is deprecated

### ISSUE THREAD

**Issue by soulclown** [pughpugh/react-countdown-clock#27]
Just installed this module, and got the following error in the console.

```
Warning: ReactCountdownClock: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-c
lass is available on npm as a drop-in replacement.
```

**Comment by pughpugh** [comment]
I believe this has been resolved by @AaronKalair as part of PR #24 . I've not found a lot of time to go through the open issues and PRs recently. I'll see if I can make some time.

**Comment by HTaiNguyen** [comment]
Did you solve that issue yet ?

**Comment by pughpugh** [comment]
This has now been merged and published. Thanks all.
