### ISSUE TITLE
Timer briefly displays x:60 seconds instead of x:59

### ISSUE THREAD

**Issue by 7022Andre** [pughpugh/react-countdown-clock#38]
I just noticed that the timer briefly displays 60 at every full minute instead of 59, e.g. after 2:00 the timer shows briefly 1:60 before 1:59. Example from my app:
[![timer_issue.gif](https://s26.postimg.org/g6no62ad5/timer_issue.gif)](https://postimg.org/image/uput7h3hx/).

Example from [demo](http://pughpugh.github.io/react-countdown-clock)
[![timer.gif](https://s26.postimg.org/xp6b8c2d5/timer.gif)](https://postimg.org/image/5p27o1ywl/)

**Comment by pughpugh** [comment]
Sorry for the delayed response and thanks for the great bug report. I will take a look.

**Comment by pughpugh** [comment]
Thanks for reporting this. It should be fixed in 2.3.0.
