### ISSUE TITLE
Minutes & Hours

### ISSUE THREAD

**Issue by admiralPanda** [pughpugh/react-countdown-clock#4]
I'd love to see you add minutes & hours countdown in addition to seconds. It'd be super useful.

**Comment by pughpugh** [comment]
I had a play with this today, although it needs more work;

<img width="1006" alt="screen shot 2015-12-20 at 13 31 32" src="https://cloud.githubusercontent.com/assets/689998/11918176/99c852b2-a71e-11e5-92a9-903cf4bd647e.png">

I'd like to retain the ability of just showing seconds, but this could be controlled with another prop.

**Comment by admiralPanda** [comment]
Looks awesome!

**Comment by lusilva** [comment]
Any updates? Would love to use this to display a countdown on my page if it had minutes and hours.

**Comment by pughpugh** [comment]
Thanks for the reminder. I'll try and organise some time for this.

**Comment by rafmar** [comment]
Great work @pughpugh :+1: Your countdown looks gorgeous and I think it definitely needs possibility of displaying minutes and hours.

**Comment by YurkoZ** [comment]
Any news about it?

**Comment by pughpugh** [comment]
No sorry, no update. I keep meaning finish it, but life is busy at the mo. I'll keep it in mind.

**Comment by pughpugh** [comment]
I've finally got round to starting a branch for this. Hopefully be ready soon, but feel free to check it out before hand.

I've added an optional `timeFormat` prop. The default is `seconds`, but you can also use `hms`. The later one will degrade from `hh:mm:ss` to `mm:ss` to `ss` as time runs out. The start time itself still needs to be expressed in seconds.

The font size is dynamic and will attempt to use the most amount of space appropriate for the counter size and time format. You can override this to make the sizing static via the `fontSize` prop.

I've added various other props as well now. See the README for details.

https://github.com/pughpugh/react-countdown-clock/tree/minutes_and_hours

**Comment by pughpugh** [comment]
Ok, all done. This is in 1.0.8
