### ISSUE TITLE
Timer counting down went very fast after the state is updated.

### ISSUE THREAD

**Issue by MadalinaGradinaru** [pughpugh/react-countdown-clock#43]
Is there any chance to resolve this bug?

**Comment by Dyceman** [comment]
I am also having this same issue. I will see if I can solve this problem.

**Comment by pughpugh** [comment]
Thanks for the bug report. There are a few similar issues floating around. I will see if I can take a look it it over the next few days.

**Comment by pughpugh** [comment]
Fixed in [2.1.0](https://github.com/pughpugh/react-countdown-clock/tree/2.1.0).
