### ISSUE TITLE
Invariant Violation: View config not found for name canvas

### ISSUE THREAD

**Issue by lgupta54** [pughpugh/react-countdown-clock#47]
Invariant Violation: View config not found for name canvas

        <View>
                    <Text style={{textAlign: 'center'}}>
                        OTP will expire in 60 Second's
                    </Text>
                    { this.state.timer?
                        <Text style={styles.wrongNumberText} onPress={this._sendOTP}>
                            Resend OTP
                        </Text>
                        :
                        <ReactCountdownClock seconds={60}
                                             color="#000"
                                             alpha={0.9}
                                             size={300}
                                             />
                    }
                </View>

**Comment by alexsmartens** [comment]
+1

**Comment by pughpugh** [comment]
Are you trying to use this with react-native?
