### ISSUE TITLE
Can I use multiple react-countdown-clock's separately for hours, minutes and seconds.

### ISSUE THREAD

**Issue by SuryaAcube** [pughpugh/react-countdown-clock#51]
@pughpugh  What I meant to ask is can i use four separate timers each for days, hours, minutes and seconds in the same page.

- 1 clock for days
- 1 clock for hours
- 1 clock for minutes
- 1 clock for seconds.

**Comment by pughpugh** [comment]
Sorry for the delayed response. I guess you mean where they all represent a single countdown, not 4 individual countdowns. It's a nice idea, although a little beyond the scope of this project at the moment. 

I have started to think about separating out the timer logic from the front end rendering, so a user could pass in their own timer or alternative rendering. But even then, it wouldn't work out of the box for your use-case.

I'd suggest forking or creating your own timer.

**Comment by SuryaAcube** [comment]
@pughpugh Thank you for the suggestion.
