### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by sandy0201** [pughpugh/react-countdown-clock#52]
Hi,

Is this react-countdown-clock not compatible in IE?

I tried running the demo page http://pughpugh.github.io/react-countdown-clock/ in IE10 and IE11, there was an error in the console. Please see below for the error:

![image](https://user-images.githubusercontent.com/2969051/36724022-8fe5b65a-1bba-11e8-917e-059932d78510.png)

What possible work around is there to fix this?

Thank you.

Kind regards.

**Comment by pughpugh** [comment]
I believe React needs some polyfills for older browsers;

https://reactjs.org/docs/react-dom.html#browser-support

**Comment by sandy0201** [comment]
Tried it in my project now, it works with the polyfill, thank you.
