### ISSUE TITLE
npm run build fails to minify due to transpiling to ES6

### ISSUE THREAD

**Issue by sandy0201** [pughpugh/react-countdown-clock#54]
Hi,

I am building our project using Team City, and the build fails with the below error message:

Failed to minify the code from this file: 
    ./node_modules/react-countdown-clock/build/react-countdown-clock.js:1:10143 
Read more here: [http://bit.ly/2tRViJ9](http://bit.ly/2tRViJ9)

Will you be able to fix this issue?
Or if I fork, do you have any suggestions on how this can be fixed?

Looking forward to your response.

Thank you.

Kind regards.

**Comment by pughpugh** [comment]
Hi,

I suspect it was due to last two builds being run using a newer version of Webpack.

You could roll back to `2.1.0` if you want a quick fix and I will look into transpiling to ES5 later today. I imagine it's just a change to the Webpack config that is needed.

Thanks

**Comment by sandy0201** [comment]
Hi Hugh,

The build failed on version 2.1.0, therefore not sure what the issue was. Do you perhaps know?
Okay sure, that would be great.

Thanks so much!

**Comment by pughpugh** [comment]
That is a little odd. I'm pretty sure the build has changed to es6 at 2.2.0, so I'm not sure why 2.1.0 does not work. Are you getting the same build error?

I've pushed a version to master, that I believe is now ES5. Would you be able to try that, before I publish it to npm?

**Comment by sandy0201** [comment]
I haven't tried building my project again on Team City with the new version 2.3.0 yet. But I was getting the error on version 2.1.0. The error only happens on Team City build, when I build it locally on my PC it does works.

Okay sure, will try it.

Thank you.

**Comment by sandy0201** [comment]
Hi Hugh,

I tried 2.3.0, and the build also fails with the same error.

I was going to try 2.4.0, but I realise, even if I copy the new files and add it to the node_modules folder of our project, when Team City runs the steps to build the project, it will override the new files that I have copied to the node_modules folder. This is because the second step on Team City is to install npm packages.

Could you please publish it to npm then I can try again?

Thank you.

**Comment by pughpugh** [comment]
OK, published. Let me know how you get on.

**Comment by sandy0201** [comment]
The new release worked. Thank you so much for your assistance.

**Comment by pughpugh** [comment]
No problem @sandy0201 , happy to help.
