### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by noblesilence** [pughpugh/react-countdown-clock#56]
Can someone tell me how to run this project? I installed coffee-script via Terminal with `sudo npm install -g coffee-script`. 

When I try to compile it with `coffee --compile coffee/react-countdown-clock.coffee`, I get this error: `react-countdown-clock.coffee:198:50: error: missing / (unclosed regex)
      <canvas ref='background' {...canvasProps}></canvas>`

**Comment by pughpugh** [comment]
Hey. Check out the comments here; https://github.com/pughpugh/react-countdown-clock/issues/34#issuecomment-365738853
