### ISSUE TITLE
Error on Server-Side 

### ISSUE THREAD

**Issue by FabianSellmann** [pughpugh/react-countdown-clock#60]
`_scale: window.devicePixelRatio || 1` will throw an error since window is not defined on the server. Since this is a static property, error will be thrown already when you import the the module.

**Comment by alf182** [comment]
I have this problem too

**Comment by codesignist** [comment]
If you use next.js you can render on client side.

https://nextjs.org/docs#with-no-ssr

**Comment by jtterra** [comment]
No fixes yet ?

**Comment by pughpugh** [comment]
Thaks for reporting this. I've not got this set up to replicate, but I've pushed a fix. Let me know if there are any issues.
