### ISSUE TITLE
maintain timer state on reloading page

### ISSUE THREAD

**Issue by GMT95** [pughpugh/react-countdown-clock#61]
If I reload the page the timer also restarts,how can I keep the timer state as it was at the time of reload

**Comment by miyoshikaya** [comment]
excellent question, I was wondering that too...

**Comment by pughpugh** [comment]
There isn't currently a way create a timer in mid progress. I'm sure it would be possible with some minor tinkering, but I'm a bit short of time at the moment. I'm happy to accept a PR if anyone wants to take a crack at it. 

Alternatively, You might find it's already been implemented on one of the [forks](https://github.com/pughpugh/react-countdown-clock/network), it looks like @kolaf attempted it [here](https://github.com/kolaf/react-countdown-clock/commit/0745c7e8df5b8098477375f8e7968c2f0591fc12).

**Comment by GMT95** [comment]
Thanks for the answer @pughpugh.
