### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aucodemonkey** [pughpugh/react-countdown-clock#7]
I don't see a license for this piece of code. Is there one associated with it?

**Comment by pughpugh** [comment]
[ISC](https://opensource.org/licenses/ISC) as mentioned in the `package.json`. I could add an explicit license file, if you think it would make it easier to find.

**Comment by pughpugh** [comment]
Well I've done that now as well, which will feature in the next release I cut.

**Comment by aucodemonkey** [comment]
Sorry, brain fart last night. I didn't even think to check the package.json file. Thanks!
